# Use the official Node.js 16 image
FROM node:16

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variable
ENV PORT 8080

# Expose port 8080
EXPOSE 8080

# Command to run the application
CMD ["npm", "start"]
